# controller_list:
# - name: "scaled_pos_joint_traj_controller"
#   action_ns: follow_joint_trajectory
#   type: FollowJointTrajectory
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint


controller_list:
- name: "eff_joint_traj_controller"  # Change this to match Gazebo
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  default: True
